apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster1
  namespace: cnpg
spec:
  logLevel: info
  startDelay: 10
  stopDelay: 10
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  smartShutdownTimeout: 10
  backup:
    target: prefer-standby
    volumeSnapshot:
      online: true
      onlineConfiguration:
        immediateCheckpoint: false
        waitForArchive: true
      snapshotOwnerReference: none
    retentionPolicy: 7d
  enableSuperuserAccess: false
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
    tls:
      enabled: false
  minSyncReplicas: 1
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  enablePDB: true
  primaryUpdateMethod: switchover
  failoverDelay: 10
  postgresql:
    synchronous:
      method: any
      number: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  walStorage:
    resizeInUseVolumes: true
    size: 1Gi
  maxSyncReplicas: 2
  switchoverDelay: 3600
  storage:
    resizeInUseVolumes: true
    size: 1Gi
  primaryUpdateStrategy: unsupervised
  instances: 3
  description: pg-cluster1